### ISSUE TITLE
Search Filter of Tools

### ISSUE THREAD

**Issue by Relluem94** [Relluem94s/RelluToolbox#8]
https://relluem94.atlassian.net/browse/RTB-3

![image](https://github.com/Relluem94s/RelluToolbox/assets/6181042/1f1a315c-dc77-48fe-9d85-a03bafc56cb3)

**Comment by Relluem94** [comment]
@CallMeLeon167  @dennischrispens  this would be a easy issue, checkout branch RTB-3

**Comment by folivora97** [comment]
Wie soll das angezeigt weren? Sollen alle anderen ausgeblendet werden? Oder eine farbige Umrandung um das Element?

**Comment by folivora97** [comment]
Done in https://github.com/Relluem94s/RelluToolbox/pull/16
